### ISSUE TITLE
Bundled mbedtls has hard-coded config.h with asm enabled

### ISSUE THREAD

**Issue by richfelker** [despair86/cage#1]
This precluded building on any target without asm. Further, the conditional for `MBEDTLD_HAVE_X86_64` is wrong; it treats i386 as x86_64 and attempts to build asm which is not valid for i386.

As an aside, mbedtls is a rather bad implementation of crypto primitives, and would be better replaced by bearssl.

**Comment by despair86** [comment]
that was partially intentional: the AES-NI implementation happens to be 32-bit clean, and works if compiled as 32-bit code. Indeed, I am also looking to replace it since most of the code is unused for now (and is otherwise stripped out by LTO at least).

Thanks!

**Comment by richfelker** [comment]
It doesn't, at least not with a toolchain where -march=i486 is the default. If you want to use it on 32-bit too then there should be a check for `__sse2__` or whatever the macro indicating availability of sse2 is.

**Comment by despair86** [comment]
That should fix `-mcpu=i486` for now, unless Clang has decided not to define `__GNUC__` anymore

**Comment by richfelker** [comment]
Thanks, that fixed it!
