### ISSUE TITLE
Parallel make is broken

### ISSUE THREAD

**Issue by richfelker** [despair86/cage#2]
If I run `make -j4`, I get:

```
make[2]: *** No rule to make target `CMakeFiles/cage-crypto.dir/src/crypto/aes.c
.o', needed by `cage-keygen'.  Stop.
```

Running `make -j4` again succeeds.

**Comment by despair86** [comment]
what version of make do you have? I have 
```
$ gmake -version
GNU Make 4.2.1
Built for i386-pc-solaris2.11
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
worked fine the first time even, and using CMake 3.15.1.

**Comment by richfelker** [comment]
I'm using CMake 3.16.2, but older GNU make (3.82). However I don't think it's a GNU make version issue; the `build.make` files CMake generates look wrong. `CMakeFiles/cage-crypto.dir/build.make` contains a rule for building `CMakeFiles/cage-crypto.dir/src/crypto/aes.c.o` and all the other crypto object files, but `CMakeFiles/cage-keygen.dir/build.make` has no rules for them but does have dependencies on them. Thus it works if the `cage-crypto` build ran/finished first, but not if they run in parallel and get unlucky.

**Comment by richfelker** [comment]
I think cage-keygen should have a dependency on completion of cage-crypto build, no?

**Comment by despair86** [comment]
ohhhh

I saw this with the Microsoft C CMake generator (Visual Studio 2008), I might just switch back to plain old static libraries if this is the case.
